[package]
name = "data_provider"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
zeroize = { version = "1", features = ["zeroize_derive"] }
rand = "0.8"
rand_chacha = "0.3"
lazy_static = "1.4"
ic_bls12_381 = { version = "0.8.0", default-features = false, features = ["pairings", "alloc", "experimental", "zeroize"] }
sha2 = "0.9"
sha3 = "0.9"
pairing = "0.22"
subtle = "2.5"
wasm-bindgen = { version = "0.2.84", optional = true }
# Enable `custom` feature of getrandom dependency. See lib.rs for more details.
getrandom = { version = "0.2", features = ["custom"], optional = true }
candid = "0.8"
ic-cdk = "0.7"
ic-cdk-timers = "0.1" # Feel free to remove this dependency if you don't need timers
hex = "0.4"
serde = "1"


[dev-dependencies]
hex = "0.4"

[features]
default = ["js"]
js = ["dep:wasm-bindgen", "dep:getrandom"]